---
vcenter_hostname: vcsa-1.local.lan
vcenter_username: "{{ lookup('hashi_vault','secret=secret/vsphere/vcsa:vsphere_username') }}"
vcenter_password: "{{ lookup('hashi_vault','secret=secret/vsphere/vcsa:vsphere_password') }}"
vcenter_datacenter: "HomeLab Datacenter"
vm_snapshot_name: "snapshot"
snap_description: "snapshot"

