- name: Get vm disk facts
  community.vmware.vmware_guest_disk_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vm_name }}"
    validate_certs: false
  register: disk_info

- name: Set unit_number if not defined
  ansible.builtin.set_fact:
    unit_number: "{{ ((disk_info['guest_disk_info'] | count) + 1) | int }}"
  when: unit_number is not defined

- name: Add disk to virtual machine
  community.vmware.vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vm_name }}"
    validate_certs: false
    disk:
      - size_gb: "{{ vmdk_size }}"
        type: thin
        datastore: "{{ datastore }}"
        state: present
        scsi_controller: 0
        unit_number: "{{ unit_number }}"
        scsi_type: 'paravirtual'
        disk_mode: 'persistent'
